### ISSUE TITLE
Amazing dump 😨 

### ISSUE THREAD

**Issue by thoma5s** [debugCrackingYourShittyApplication/Honeycomb-Dump#1]

**Comment by debugCrackingYourShittyApplication** [comment]
can you add some more decompilers on your shitty app plz ty

**Comment by debugCrackingYourShittyApplication** [comment]
i mean the most recent version is decompiled too which is pretty cool

**Comment by feticks** [comment]
Please tell me that you understand the fact that you dumped obfuscated source... if I removed the anti decompiler it would be the exact same if you dropped it into dnSpy lol...

**Comment by AzgarDev** [comment]
First of all, decompilers does not equal debuggers, secondly, you're a fucking retard. You didn't deobfuscate anything, you literally dumped the files and you really think the application's source-code will magically appear by just dumping it, learn how to reverse-engineer you dumbfuck.
